package com.dvoiss.sensorannotations;

import org.junit.Test;

import static com.dvoiss.sensorannotations.TestUtils.shouldGenerateBindingSource;

public class BindAllAnnotationsTest {

    @Test
    public void bindAllSucceeds() {
        String source = "package test;\n"
            + "\n"
            + "import android.app.Activity;\n"
            + "import android.hardware.Sensor;\n"
            + "import android.hardware.SensorEvent;\n"
            + "import android.hardware.TriggerEvent;\n"
            + "import com.dvoiss.sensorannotations.OnAccuracyChanged;\n"
            + "import com.dvoiss.sensorannotations.OnSensorChanged;\n"
            + "import com.dvoiss.sensorannotations.OnSensorNotAvailable;\n"
            + "import com.dvoiss.sensorannotations.OnTrigger;\n"
            + "\n"
            + "public class Test extends Activity {\n"
            + "    @OnSensorChanged(Sensor.TYPE_MAGNETIC_FIELD)\n"
            + "    void testMagneticFieldSensorChanged(SensorEvent event) {}\n"
            + "\n"
            + "    @OnSensorNotAvailable(Sensor.TYPE_MAGNETIC_FIELD)\n"
            + "    void testMagneticFieldSensorNotAvailable() {}\n"
            + "\n"
            + "    @OnAccuracyChanged(Sensor.TYPE_MAGNETIC_FIELD)\n"
            + "    void testMagneticFieldAccuracyChanged(Sensor sensor, int accuracy) {}\n"
            + "\n"
            + "    @OnTrigger\n"
            + "    public void testSignificantMotionTrigger(TriggerEvent event) {}\n"
            + "}";

        String bindingSource = "// This class is generated code from Sensor Lib. Do not modify!\n"
            + "package test;\n"
            + "\n"
            + "import static android.content.Context.SENSOR_SERVICE;\n"
            + "\n"
            + "import android.content.Context;\n"
            + "import android.hardware.Sensor;\n"
            + "import android.hardware.SensorEventListener;\n"
            + "import android.hardware.SensorManager;\n"
            + "import android.hardware.TriggerEventListener;\n"
            + "import com.dvoiss.sensorannotations.internal.EventListenerWrapper;\n"
            + "import com.dvoiss.sensorannotations.internal.SensorBinder;\n"
            + "import com.dvoiss.sensorannotations.internal.SensorEventListenerWrapper;\n"
            + "import com.dvoiss.sensorannotations.internal.TriggerEventListenerWrapper;\n"
            + "import java.lang.Override;\n"
            + "import java.util.ArrayList;\n"
            + "import java.util.List;\n"
            + "\n"
            + "final class Test$$SensorBinder implements SensorBinder<Test> {\n"
            + "  private final SensorManager sensorManager;\n"
            + "\n"
            + "  private final List<EventListenerWrapper> listeners;\n"
            + "\n"
            + "  public Test$$SensorBinder(Context context, final Test target) {\n"
            + "    this.sensorManager = (SensorManager) context.getSystemService(SENSOR_SERVICE);\n"
            + "    this.listeners = new ArrayList();\n"
            + "    this.listeners.add(new SensorEventListenerWrapper(2, 3, new SensorEventListener() {\n"
            + "          @java.lang.Override\n"
            + "          public void onSensorChanged(android.hardware.SensorEvent event) {\n"
            + "            target.testMagneticFieldSensorChanged(event);\n"
            + "          }\n"
            + "          @java.lang.Override\n"
            + "          public void onAccuracyChanged(android.hardware.Sensor sensor, int accuracy) {\n"
            + "            target.testMagneticFieldAccuracyChanged(sensor, accuracy);\n"
            + "          }\n"
            + "        }));\n"
            + "    this.listeners.add(new TriggerEventListenerWrapper(new TriggerEventListener() {\n"
            + "          @java.lang.Override\n"
            + "          public void onTrigger(android.hardware.TriggerEvent event) {\n"
            + "            target.testSignificantMotionTrigger(event);\n"
            + "          }\n"
            + "        }));\n"
            + "  }\n"
            + "\n"
            + "  @Override\n"
            + "  public void bind(final Test target) {\n"
            + "    int sensorType;\n"
            + "    Sensor sensor;\n"
            + "    for (EventListenerWrapper wrapper : listeners) {\n"
            + "      sensorType = wrapper.getSensorType();\n"
            + "      sensor = wrapper.getSensor(sensorManager);\n"
            + "      if (sensor == null) {\n"
            + "        if (sensorType == 2) {\n"
            + "          target.testMagneticFieldSensorNotAvailable();\n"
            + "        }"
            + "        continue;\n"
            + "      }\n"
            + "      wrapper.registerListener(sensorManager);\n"
            + "    }\n"
            + "  }\n"
            + "\n"
            + "  @Override\n"
            + "  public void unbind() {\n"
            + "    if (this.sensorManager != null) {\n"
            + "      for (EventListenerWrapper wrapper : listeners) {\n"
            + "        wrapper.unregisterListener(sensorManager);\n"
            + "      }\n"
            + "    }\n"
            + "  }\n"
            + "}\n";

        shouldGenerateBindingSource(source, bindingSource);
    }
}
